class EventEmitter{
  constructor(){
    this.queue={};
  }
  on(event,callback){
    if(!(this.queue.hasOwnProperty(event))){
      this.queue[event]=[];
    }
    this.queue[event].push(callback);
    console.log("on",event);
  }
  emit(event,...params){
    if(this.queue.hasOwnProperty(event)){
      this.queue[event].forEach(callback=>callback(...params))
    }
    console.log("emit",event,params)
  }
}
module.exports={
  EventEmitter
}